CREATE VIEW VIEW_RESUMO_CLIENTES AS
SELECT 
  c.ID_CLIENTE,
  c.NOME_CLIENTE,
  ec.CIDADE,
  COUNT(DISTINCT p.ID_PEDIDO) AS QTD_PEDIDOS,
  SUM(p.VALOR_PEDIDO) AS TOTAL_GASTO,
  ROUND(AVG(p.VALOR_PEDIDO), 2) AS MEDIA_GASTA,
  SUM(pp.QUANT_PEDIDO_PRODUTO) AS TOTAL_ITENS_COMPRADOS,
  (
    SELECT h.STATUS_NOVO
    FROM Historico h
    WHERE h.ID_PEDIDO = (
      SELECT p2.ID_PEDIDO
      FROM Pedido p2
      WHERE p2.ID_CLIENTE = c.ID_CLIENTE
      ORDER BY p2.DATA_HORA_PEDIDO DESC
      LIMIT 1
    )
    ORDER BY h.DATA_HORA_ALTERACAO DESC
    LIMIT 1
  ) AS ULTIMO_STATUS
FROM Cliente c
LEFT JOIN Endereco_Cliente ec ON c.ID_CLIENTE = ec.ID_CLIENTE
LEFT JOIN Pedido p ON c.ID_CLIENTE = p.ID_CLIENTE
LEFT JOIN Produto_Pedido pp ON p.ID_PEDIDO = pp.ID_PEDIDO
GROUP BY c.ID_CLIENTE, c.NOME_CLIENTE, ec.CIDADE
ORDER BY TOTAL_GASTO DESC;


CREATE VIEW VIEW_RESUMO_PEDIDOS AS
SELECT
  p.ID_PEDIDO,
  c.NOME_CLIENTE,
  ec.CIDADE,
  p.DATA_HORA_PEDIDO,
  (
    SELECT h.STATUS_NOVO
    FROM Historico h
    WHERE h.ID_PEDIDO = p.ID_PEDIDO
    ORDER BY h.DATA_HORA_ALTERACAO DESC
    LIMIT 1
  ) AS STATUS_ATUAL,
  (
    SELECT ROUND(SUM(pr.VALOR_PRODUTO * pp.QUANT_PEDIDO_PRODUTO), 2)
    FROM Produto_Pedido pp
    JOIN Produto pr ON pp.ID_PRODUTO = pr.ID_PRODUTO
    WHERE pp.ID_PEDIDO = p.ID_PEDIDO
  ) AS VALOR_TOTAL_PEDIDO,
  (
    SELECT SUM(QUANT_PEDIDO_PRODUTO)
    FROM Produto_Pedido
    WHERE ID_PEDIDO = p.ID_PEDIDO
  ) AS QUANTIDADE_TOTAL_ITENS
FROM Pedido p
JOIN Cliente c ON p.ID_CLIENTE = c.ID_CLIENTE
LEFT JOIN Endereco_Cliente ec ON c.ID_CLIENTE = ec.ID_CLIENTE;
